### ISSUE TITLE
ToDo list of examples

### ISSUE THREAD

**Issue by guillesanbri** [ivy-llc/demos#2]
This issue lists all the examples that we should work on, if you have suggestions about new examples you can post them [here](https://github.com/unifyai/demos/issues/1). 

If you want to work on any of these examples, please **create an issue with the same name as the list-item bold name and edit this comment to replace the name with the issue link** so that everybody can know who is working on what :smile: .

When creating a new notebook, please use the name of the list item in camel case (i.e. `First Example with Ivy` -> `first_example_with_ivy.ipynb`).

A few points:
- There will be tags classifying notebooks in related to "Ivy as a framework" and related to "Ivy as a transpiler"
- Notebooks with 🚨 should be prioritized!
- Notebooks in learn the basics should be extremely short and to the point, tutorials should be mid-length, with examples and demos probably being more lengthy and involved

---
- [ ] 🚨 Quickstart (framework)(transpiler)
### Learn the basics
- [x] 🚨 Write framework-agnostic code (framework)
- [x] 🚨 Unify code (transpiler)
- [x] 🚨 Compile code (framework)(transpiler)
- [x] 🚨 Transpile code (transpiler)
- [x] 🚨 Lazy vs Eager (framework)(transpiler)
- [x] 🚨 How to use decorators (framework)(transpiler)
- [x] 🚨 Transpile any library (transpiler)
- [x] 🚨 Transpile any model (transpiler)
- [ ] 🚨 Write a module using Ivy (framework)
### Tutorials
- [ ] 🚨 Developing a convolutional network using Ivy (framework)
- [ ] Developing a transformer using Ivy (framework)
- [x] 🚨 Transpiling a torch model to build on top of it (transpiler)
- [x] #15
- [ ] 🚨 Transpiling a haiku model to build on top of it (transpiler)
### Examples and demos
- [ ] 🚨 #6
- [ ] 🚨 (?) Developing DeepMind's PerceiverIO using Ivy (framework) (?)
- [ ] Deploying a PyTorch model using TFLite (transpiler)
- [ ] Running a timm model in JAX using TPUs (transpiler)
- [ ] Benchmarking performance - Benchmark of the performance of a complex model after transpiling it to different backends (transpiler)
- [ ] Using fvcore to measure FLOPs in a keras model - this example should explore this kind of tools and showcase how transpiling models can help compare them in a more fair and easy way (e.g. compare various models in different frameworks calculating the FLOPs with the same tool) (transpiler)
- [ ] Transpiling a model from Hugging Face - add something else here (transpiler)
---

### To be categorized (probably in the basics):
- [ ] Debugging graphs (framework)(transpiler)
- [ ] Exploring the graph (show_graph) (framework)(transpiler)

**Comment by abhi2596** [comment]
Hi, I am interested in contributing to this issue of developing a convolutional network using Ivy framework. I wanted to know if this is what should be done. https://colab.research.google.com/drive/1UiwsWBVlEXrZXkS90311kguq9mMftZIu?usp=sharing
